# THIS FILE WE SHOULD PUT THE CODE TO ACTUALLY FIND THE CLUES.
# THIS SHOULD BE ONE BIG FUNCTION WHICH JUST RETURNS THE CLUE
# THIS WAY WE CAN JUST CALL THIS FUNCTION FROM THE codenames.py AND IT WILL GIVE BACK THE CLUE